name: Deploy to S3 + CloudFront

on:
  push:
    branches: [ main ] # or whatever your main branch is
  workflow_dispatch: # allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22' # or your preferred version
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: af-south-1 # change to your region

    - name: Sync files to S3
      run: |
        aws s3 sync dist/clear-finance-web/browser s3://clearfinance --delete

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id E1MW1A7FB78HDV \
          --paths "/*"
